ViHard: projects/vihard/inc/vihard.h File Reference
vihard.h File Reference
#include <stdint.h>
#include "sapi.h"
Macros
#define BOARD_EDU_CIAA_NXP
#define VIHARD_SERIAL_PORT UART_USB
#define VIHARD_BAUDRATE 115200
#define CLOCK_SPEED_MHZ 204
#define UART_CONFIG(baudrate) uartConfig(VIHARD_SERIAL_PORT, baudrate)
#define UART_READ_BYTE(byteToRead) uartReadByte(VIHARD_SERIAL_PORT, &byteToRead)
#define UART_WRITE_BYTE(byteToWrite) uartWriteByte(VIHARD_SERIAL_PORT, (uint8_t) byteToWrite)
#define FALSE 0
#define TRUE (!FALSE)
Typedefs
typedef uint8_t bool_t
typedef enum _LcdLine LcdLine_t
typedef enum _ViHardPeriph ViHardPeriph_t
Enumerations
enum _LcdLine { LCD_LINE_ALL = '0', LCD_LINE_FIRST = '1', LCD_LINE_SECOND = '2', LCD_LINE_THIRD = '3' }
enum _ViHardPeriph {
VH_LEDR = 'a', VH_LEDG = 'b', VH_LEDB = 'z', VH_LED1 = 'c',
VH_LED2 = 'd', VH_LED3 = 'e', VH_LED4 = 'f', VH_TEC1 = 'g',
VH_TEC2 = 'h', VH_TEC3 = 'i', VH_TEC4 = 'j', VH_ADC_CH1 = 'k',
VH_DAC_CH1 = 'n', VH_LCD1 = 'o', VH_7SEG = 'p'
}
Functions
bool_t Vh_BoardConfig (uint32_t baudRate)
bool_t Vh_GpioRead (ViHardPeriph_t gpioPin)
void Vh_GpioWrite (ViHardPeriph_t gpioPin, bool_t pinState)
void Vh_GpioToggle (ViHardPeriph_t gpioPin)
uint16_t Vh_AdcRead (ViHardPeriph_t adcChannel)
void Vh_DacWrite (ViHardPeriph_t dacChannel, uint16_t dacValue)
void Vh_7SegmentsWrite (ViHardPeriph_t display7Segs, uint8_t asciiToShow)
void Vh_LcdWriteString (ViHardPeriph_t displayLcd, LcdLine_t line, char *str)
Macro Definition Documentation
#define BOARD_EDU_CIAA_NXP
Definition at line 41 of file vihard.h.
#define CLOCK_SPEED_MHZ 204
Definition at line 83 of file vihard.h.
#define FALSE 0
Definition at line 111 of file vihard.h.
Referenced by Vh_AdcRead(), and Vh_GpioRead().
#define TRUE (!FALSE)
Definition at line 112 of file vihard.h.
Referenced by Vh_AdcRead(), Vh_BoardConfig(), Vh_GpioRead(), and Vh_GpioWrite().
#define UART_CONFIG (baudrate) uartConfig(VIHARD_SERIAL_PORT, baudrate)
Definition at line 85 of file vihard.h.
Referenced by Vh_BoardConfig().
#define UART_READ_BYTE (byteToRead) uartReadByte(VIHARD_SERIAL_PORT, &byteToRead)
Definition at line 86 of file vihard.h.
#define UART_WRITE_BYTE (byteToWrite) uartWriteByte(VIHARD_SERIAL_PORT, (uint8_t) byteToWrite)
Definition at line 87 of file vihard.h.
#define VIHARD_BAUDRATE 115200
Definition at line 82 of file vihard.h.
Referenced by main().
#define VIHARD_SERIAL_PORT UART_USB
Definition at line 81 of file vihard.h.
Typedef Documentation
typedef uint8_t bool_t
Definition at line 116 of file vihard.h.
typedef enum _LcdLine LcdLine_t
Posibles valores que puede recibir la funcion de escribir un texto sobre el display LCD. LCD_LINE_ALL escribe un mensaje multilinea, los demas valores escriben sobre la primer, segunda o tercer linea del LCD.
typedef enum _ViHardPeriph ViHardPeriph_t
Mapa de perifericos virtuales a los que se puede acceder.
Enumeration Type Documentation
enum _LcdLine
Posibles valores que puede recibir la funcion de escribir un texto sobre el display LCD. LCD_LINE_ALL escribe un mensaje multilinea, los demas valores escriben sobre la primer, segunda o tercer linea del LCD.
Enumerator
LCD_LINE_ALL
LCD_LINE_ALL.
LCD_LINE_FIRST
LCD_LINE_FIRST.
LCD_LINE_SECOND
LCD_LINE_SECOND.
LCD_LINE_THIRD
LCD_LINE_THIRD.
Definition at line 123 of file vihard.h.
enum _ViHardPeriph
Mapa de perifericos virtuales a los que se puede acceder.
Enumerator
VH_LEDR
VH_LEDR.
VH_LEDG
VH_LEDG.
VH_LEDB
VH_LEDB.
VH_LED1
VH_LED1.
VH_LED2
VH_LED2.
VH_LED3
VH_LED3.
VH_LED4
VH_LED4.
VH_TEC1
VH_TEC1.
VH_TEC2
VH_TEC2.
VH_TEC3
VH_TEC3.
VH_TEC4
VH_TEC4.
VH_ADC_CH1
VH_ADC_CH1.
VH_DAC_CH1
VH_DAC_CH1.
VH_LCD1
VH_LCD1.
VH_7SEG
VH_7SEG.
Definition at line 133 of file vihard.h.
Function Documentation
void Vh_7SegmentsWrite (ViHardPeriph_t display7Segs, uint8_t asciiToShow)
Escribe un caracter ASCII sobre el periferico display 7 segmentos. A diferencia de un display 7 segmentos real, este display, por el tipo de letra elegido, puede escribir cualquier caracter ASCII sobre el display a diferencia de uno tradicional que puede escribir del 0-9 y A-F.
Parameters
display periferico del display 7 segmentos.
valueToShow caracter ASCII a mostrar sobre el display.
Definition at line 588 of file vihard.c.
References COMMAND_END, COMMAND_INIT, COMMAND_SEPARATOR, and VH_7SEG_WRITE.
uint16_t Vh_AdcRead (ViHardPeriph_t adcChannel)
Realiza una lectura sobre un pin analogico. La conversion ADC tiene una resolucion de 10 bits, por lo que, sus valores estan comprendidos entre 0 y 1023.
Parameters
virtualAdcPin pin analogico virtual a leer.
Returns
valor analogico leido.
Definition at line 446 of file vihard.c.
References COMMAND_END, COMMAND_INIT, COMMAND_SEPARATOR, FALSE, MAX_ANALOG_VALUE, TRUE, VH_ADC_READ, VH_COMM_REQUEST, and VH_COMM_RESPONSE.
bool_t Vh_BoardConfig (uint32_t baudRate)
Configura el puerto serie por el que se va a comunicar el sistema embebido con la plataforma de hardware virtual. Se elige que solo se reciba la velocidad de la uart y no a que uart se va a conectar ya que el framework de Arduino unicamente recibe como parametro la velocidad de conexion.
Parameters
baudRate velocidad de transmision.
Returns
1 siempre.
Definition at line 316 of file vihard.c.
References TRUE, and UART_CONFIG.
Referenced by main().
void Vh_DacWrite (ViHardPeriph_t dacChannel, uint16_t dacValue)
Escribe un valor analogico sobre una salida analogica. El valor a escribir es de 10 bits, por lo que, sus valores estan comprendidos entre 0 y 1023.
Parameters
dacChannel pin analogico a escribir.
dacValue valor de 10 bits a escribir.
Definition at line 544 of file vihard.c.
References COMMAND_END, COMMAND_INIT, COMMAND_SEPARATOR, MAX_ANALOG_VALUE, and VH_DAC_WRITE.
bool_t Vh_GpioRead (ViHardPeriph_t gpioPin)
Lee el estado logico de un pin virtual.
Parameters
virtualGpioPin pin virtual a leer.
Returns
estado logico leido.
Definition at line 355 of file vihard.c.
References COMMAND_END, COMMAND_INIT, COMMAND_SEPARATOR, FALSE, TRUE, VH_COMM_REQUEST, VH_COMM_RESPONSE, VH_GPIO_HIGH, VH_GPIO_LOW, and VH_GPIO_READ.
Referenced by Vh_GpioToggle().
void Vh_GpioToggle (ViHardPeriph_t gpioPin)
Invierte el estado logico de un pin. Notar que para que esta accion se realice, el pin a invertir su estado debe ser un pin de salida.
Parameters
virtualGpioPin pin a invertir el estado logico.
Definition at line 434 of file vihard.c.
References Vh_GpioRead(), and Vh_GpioWrite().
void Vh_GpioWrite (ViHardPeriph_t gpioPin, bool_t pinState)
Escribe un estado logico en un pin virtual.
Parameters
virtualGpioPin pin virtual a escribir.
pinState estado logico a enviar.
Definition at line 330 of file vihard.c.
References COMMAND_END, COMMAND_INIT, COMMAND_SEPARATOR, TRUE, VH_GPIO_HIGH, VH_GPIO_LOW, and VH_GPIO_WRITE.
Referenced by Vh_GpioToggle().
void Vh_LcdWriteString (ViHardPeriph_t displayLcd, LcdLine_t line, char * str)
Escribe un texto sobre el periferico display LCD. Como en el caso de un display LCD real, se puede seleccionar la linea sobre la cual escribir el texto.
Parameters
display periferico del display lcd sobre el cual escribir.
lcdLine la linea sobre la cual escribir el mensaje, los posibles valores de la lineas son: — LCD_LINE_ALL: escribe un mensaje multilinea. — LCD_LINE_FIRST: escribe en la primer linea. — LCD_LINE_SECOND: escribe en la segunda linea. — LCD_LINE_THIRD: escribe en la tercer linea.
stringToWrite cadena a escribir
Definition at line 621 of file vihard.c.
References COMMAND_END, COMMAND_INIT, COMMAND_SEPARATOR, and VH_LCD_WRITE_STRING.